bucket_name: "www.example.com"
domain_name: "www.example.com"
CNAMEs:
  - "example.com"
  - "www.example.com"
route_53_hosted_zone_id: "Z05234556KK8DIAQM"
route_53_hosted_zone_name: "example.com"
stack_name: "www-example-com-stack"
# these are the optional parameters
aws_profile_name: "default"
support_bucket_name: "webflow-aws-support"
support_stack_name: "WebflowAWSSupport"